### ISSUE TITLE
bvm use does not update path

### ISSUE THREAD

**Issue by muuvmuuv** [dsherret/bvm#26]
Testing `use` on my latest macOS seems to not work as seamless as I though initially. Below is my terminal output and zshrc part for `bvm`. 

```zsh
# BVM
export BVM_INSTALL_DIR="$HOME/.bvm"
source "$BVM_INSTALL_DIR/bin/bvm-init"
export PATH=$(bvm get-new-path)
```

```
at [$time]($style) ❯ bvm use node 12

~/Downloads took 856ms
at [$time]($style) ❯ node --version
v14.12.0

~/Downloads
at [$time]($style) ❯ export PATH=$(bvm get-new-path)

~/Downloads
at [$time]($style) ❯ node --version
v14.12.0

~/Downloads
at [$time]($style) ❯ bvm get-new-path
/Users/marvinheilemann/.bvm/bin:/shims:/Users/marvinheilemann/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/marvinheilemann/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/marvinheilemann/.deno/bin:/Users/marvinheilemann/.cargo/bin:/Users/marvinheilemann/.go/bin:/usr/local/opt/go/libexec/bin:/Users/marvinheilemann/.local/bin:/usr/local/opt/fzf/bin:/Users/marvinheilemann/.bvm/binaries/nodejs/node/12.18.4/npm_bin
```

I see that a new path is generated with the node 12 binaries but only for npm. Anyway I think this is a little too difficult to always call `get-new-path` (when using `use` it says I should run that). From my expectations I thought using `$BVM_INSTALL_DIR/bin` in path would be enough. So when I install node it just symlinks the binary of node into `$BVM_INSTALL_DIR/bin/node`. I think nvm does it that way.

Another thing I noticed is that when using `use` without having a node registry it does nothing. Would be cool if it would ask if it should use the bvm.land default registry, same for `install`. So a use could simplify the installation process with `bvm use -y node 12` without having it in the registry before.

**Comment by muuvmuuv** [comment]
Ah, just noticed that the correct version is symlinked into `$HOME/.bvm/shims/node` but `bvm get-new-path` does not include it. Maybe a better approach would be to say the user should add this to zshrc/bashrc `export PATH="$BVM_INSTALL_DIR/shims:$PATH"` instead of a command?

**Comment by muuvmuuv** [comment]
This works without using the command out-the-box ^^

```
~/Downloads took 491ms
at [$time]($style) ❯ echo $PATH
/Users/marvinheilemann/.bvm/shims:/Users/marvinheilemann/.bvm/bin:/shims:/Users/marvinheilemann/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/marvinheilemann/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/marvinheilemann/.deno/bin:/Users/marvinheilemann/.cargo/bin:/Users/marvinheilemann/.go/bin:/usr/local/opt/go/libexec/bin:/Users/marvinheilemann/.local/bin:/usr/local/opt/fzf/bin

~/Downloads
at [$time]($style) ❯ node --version
v14.13.0

~/Downloads
at [$time]($style) ❯ bvm use node 12
The path has changed based. To update it run:
export PATH=$(bvm get-new-path)

~/Downloads took 915ms
at [$time]($style) ❯ node --version
v12.18.4
```

**Comment by muuvmuuv** [comment]
Found the problem! I just thought why then calling `bvm-init`?  Yep, there is a typo in the init script:

```
                                    here it says `BVM_DATA_DIR` which does not exists so in path it is just `/shims`
  export PATH="$BVM_INSTALL_DIR/bin:$BVM_DATA_DIR/shims:$PATH"
```

**Comment by dsherret** [comment]
I'm glad you figured it out and thanks again for the PR! It will be more stable once #25 is implemented.
