### ISSUE TITLE
Tests fails on wsl 

### ISSUE THREAD

**Issue by veritem** [dsherret/bvm#56]
![image](https://user-images.githubusercontent.com/53856673/139914255-0f07f29a-e71a-4708-bd83-73a172c88d48.png)
I'm not quite sure what's causing this to happen.

**Comment by dsherret** [comment]
@veritem hmmm strange. It seems to not be creating the zip file in this script:

https://github.com/bvm/bvm/blob/main/cli/tests/setup_args_test_util.sh

Do you have a `zip` command? I think we should change that script to fail when a command fails.

**Comment by veritem** [comment]
No I didn't have `zip` command

**Comment by dsherret** [comment]
I updated the script to fail if a command doesn't exist. I believe you just need to do `sudo apt install zip` to get this to work.
