### ISSUE TITLE
Installation script doesn't set to environment variables 

### ISSUE THREAD

**Issue by veritem** [dsherret/bvm#57]
I'm on ubuntu  20.04, the installation doesn't set environment variable 

![image](https://user-images.githubusercontent.com/53856673/139941817-a810ac53-cb28-48c7-8afd-68a48fee1898.png)

Even if you close the terminal and open it again. The issue seems to be with installation script.

**Comment by dsherret** [comment]
@veritem I've improved the installation instructions. Could you delete your `$HOME/.bvm/bin` folder and try again?

**Comment by veritem** [comment]
Fixed thanks
